// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileAngular.Models;

#nullable disable

namespace MobileAngular.Migrations
{
    [DbContext(typeof(MobileContext))]
    [Migration("20250916055950_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MobileAngular.Models.Mobile", b =>
                {
                    b.Property<int>("MobileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MobileId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MobileId");

                    b.ToTable("Mobiles");

                    b.HasData(
                        new
                        {
                            MobileId = 1,
                            Brand = "Apple",
                            ModelName = "iPhone 13",
                            Price = 999.99m
                        },
                        new
                        {
                            MobileId = 2,
                            Brand = "Samsung",
                            ModelName = "Galaxy S21",
                            Price = 799.99m
                        },
                        new
                        {
                            MobileId = 3,
                            Brand = "Google",
                            ModelName = "Pixel 6",
                            Price = 599.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
